AffA: sometimes feels a good feeling
AffB: has a bad feeling sometimes
AutA: moves around on its own
AutB: can make a noise all by itself
PerA: is able to tell if there's a loud sound
PerB: can tell if there's a loud sound
PhyA: is brown and orange
PhyB: weighs two pounds
